[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SERVER_URL = "https://screenshare-signaling-production.up.railway.app"
  NODE_VERSION = "18"