# Netlify configuration for Next.js deployment
[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/.next"

[build.environment]
  NEXT_PUBLIC_SERVER_URL = "https://screenshare-signaling-production.up.railway.app"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"